# Install script for directory: /opt/nordic/ncs/v1.6.0/zephyr

# Set the install prefix
if(NOT DEFINED CMAKE_INSTALL_PREFIX)
  set(CMAKE_INSTALL_PREFIX "/opt/nordic/ncs/v1.6.0/toolchain")
endif()
string(REGEX REPLACE "/$" "" CMAKE_INSTALL_PREFIX "${CMAKE_INSTALL_PREFIX}")

# Set the install configuration name.
if(NOT DEFINED CMAKE_INSTALL_CONFIG_NAME)
  if(BUILD_TYPE)
    string(REGEX REPLACE "^[^A-Za-z0-9_]+" ""
           CMAKE_INSTALL_CONFIG_NAME "${BUILD_TYPE}")
  else()
    set(CMAKE_INSTALL_CONFIG_NAME "")
  endif()
  message(STATUS "Install configuration: \"${CMAKE_INSTALL_CONFIG_NAME}\"")
endif()

# Set the component getting installed.
if(NOT CMAKE_INSTALL_COMPONENT)
  if(COMPONENT)
    message(STATUS "Install component: \"${COMPONENT}\"")
    set(CMAKE_INSTALL_COMPONENT "${COMPONENT}")
  else()
    set(CMAKE_INSTALL_COMPONENT)
  endif()
endif()

# Is this installation the result of a crosscompile?
if(NOT DEFINED CMAKE_CROSSCOMPILING)
  set(CMAKE_CROSSCOMPILING "TRUE")
endif()

if(NOT CMAKE_INSTALL_LOCAL_ONLY)
  # Include the install script for each subdirectory.
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/arch/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/lib/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/soc/arm/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/boards/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/subsys/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/drivers/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/nrf/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/openthread/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/mcuboot/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/trusted-firmware-m/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/cjson/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/pelion-dm/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/cddl-gen/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/memfault-firmware-sdk/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/cmsis/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/canopennode/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/civetweb/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/fatfs/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/hal_nordic/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/st/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/libmetal/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/lvgl/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/mbedtls/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/mcumgr/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/open-amp/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/loramac-node/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/segger/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/tinycbor/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/tinycrypt/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/littlefs/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/mipi-sys-t/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/nrf_hw_models/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/TraceRecorder/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/nrfxlib/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/modules/connectedhomeip/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/kernel/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/cmake/flash/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/cmake/usage/cmake_install.cmake")
  include("/opt/nordic/ncs/v1.6.0/nrf/applications/connectivity_bridge/build_thingy91_nrf52840/mcuboot/zephyr/cmake/reports/cmake_install.cmake")

endif()

